# Задание: анализ данных по планетам (astronomical_observations.csv)

1. Загрузить CSV; info(), shape, head(), tail()  
2. Выделить Марс и Земля (loc)  
3. Планеты с диаметром > 10000 км (loc)  
4. Планеты: спутников > 3 и температура поверхности < 0  
5. Сортировка по возрастанию диаметра  
6. Максимальное количество спутников  
7. Минимальная масса  
8. Среднее (среднеарифметическое) диаметра  
9. Медиана диаметра  
10. Сумма масс всех планет  
11. Столбец «категория планеты» по массе: &lt;10 — Легкая, &lt;1000 — Средняя, ≥1000 — Тяжелая (apply)  
12. Выгрузка в xlsx

In [2]:
# Задание 1: загрузка данных и обзор
import pandas as pd

df = pd.read_csv("astronomical_observations.csv", encoding="utf-8")
df_climate = pd.read_csv("climate.csv", encoding="utf-8")

# Основная таблица — планеты
print("=== info() ===")
df.info()
print("\n=== shape ===")
print(df.shape)
print("\n=== head() ===")
df.head()

=== info() ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Название планеты               8 non-null      object
 1   Тип планеты                    8 non-null      object
 2   Диаметр (км)                   8 non-null      int64
 3   Масса (10^24 кг)               8 non-null      float64
 4   Расстояние до Солнца (млн км)  8 non-null      float64
 5   Количество спутников           8 non-null      int64
 6   Температура поверхности (°C)   8 non-null      int64
dtypes: float64(2), int64(3), object(2)
memory usage: 580.0+ bytes

=== shape ===
(8, 7)

=== head() ===

,Название планеты,Тип планеты,Диаметр (км),Масса (10^24 кг),Расстояние до Солнца (млн км),Количество спутников,Температура поверхности (°C)
0,Меркурий,Террестриальная,4879,0.33,57.9,0,167
1,Венера,Террестриальная,12104,4.87,108.2,0,464
2,Земля,Террестриальная,12742,5.97,149.6,1,15
3,Марс,Террестриальная,6779,0.64,227.9,2,-65
4,Юпитер,Газовый гигант,139820,1898.00,778.5,79,-110

In [ ]:
df.tail()

In [4]:
# Задание 2: Марс и Земля — loc
df.loc[df["Название планеты"].isin(["Марс", "Земля"])]

,Название планеты,Тип планеты,Диаметр (км),Масса (10^24 кг),Расстояние до Солнца (млн км),Количество спутников,Температура поверхности (°C)
2,Земля,Террестриальная,12742,5.97,149.6,1,15
3,Марс,Террестриальная,6779,0.64,227.9,2,-65

In [5]:
# Задание 3: планеты с диаметром более 10000 км — loc
df.loc[df["Диаметр (км)"] > 10000]

,Название планеты,Тип планеты,Диаметр (км),Масса (10^24 кг),Расстояние до Солнца (млн км),Количество спутников,Температура поверхности (°C)
1,Венера,Террестриальная,12104,4.87,108.2,0,464
2,Земля,Террестриальная,12742,5.97,149.6,1,15
4,Юпитер,Газовый гигант,139820,1898.00,778.5,79,-110
5,Сатурн,Газовый гигант,116460,568.00,1433.5,83,-140
6,Уран,Ледяной гигант,50724,86.80,2872.5,27,-195
7,Нептун,Ледяной гигант,49244,102.00,4495.1,14,-200

In [6]:
# Задание 4: более 3 спутников и температура поверхности < 0
df.loc[(df["Количество спутников"] > 3) & (df["Температура поверхности (°C)"] < 0)]

,Название планеты,Тип планеты,Диаметр (км),Масса (10^24 кг),Расстояние до Солнца (млн км),Количество спутников,Температура поверхности (°C)
4,Юпитер,Газовый гигант,139820,1898.0,778.5,79,-110
5,Сатурн,Газовый гигант,116460,568.0,1433.5,83,-140
6,Уран,Ледяной гигант,50724,86.8,2872.5,27,-195
7,Нептун,Ледяной гигант,49244,102.0,4495.1,14,-200

In [7]:
# Задание 5: сортировка по возрастанию диаметра
df_sorted = df.sort_values("Диаметр (км)")
df_sorted

,Название планеты,Тип планеты,Диаметр (км),Масса (10^24 кг),Расстояние до Солнца (млн км),Количество спутников,Температура поверхности (°C)
0,Меркурий,Террестриальная,4879,0.33,57.9,0,167
3,Марс,Террестриальная,6779,0.64,227.9,2,-65
1,Венера,Террестриальная,12104,4.87,108.2,0,464
2,Земля,Террестриальная,12742,5.97,149.6,1,15
7,Нептун,Ледяной гигант,49244,102.00,4495.1,14,-200
6,Уран,Ледяной гигант,50724,86.80,2872.5,27,-195
5,Сатурн,Газовый гигант,116460,568.00,1433.5,83,-140
4,Юпитер,Газовый гигант,139820,1898.00,778.5,79,-110

In [ ]:
# Задание 6: максимальное количество спутников
df["Количество спутников"].max()

In [ ]:
# Задание 7: минимальная масса планеты
df["Масса (10^24 кг)"].min()

In [ ]:
# Задание 8: среднее (среднеарифметическое) диаметра
df["Диаметр (км)"].mean()

In [ ]:
# Задание 9: медиана диаметра
df["Диаметр (км)"].median()

In [ ]:
# Задание 10: сумма масс всех планет
df["Масса (10^24 кг)"].sum()

In [ ]:
# Задание 11: столбец «категория планеты» по массе (apply)
def category_by_mass(m):
    if m < 10:
        return "Легкая"
    if m < 1000:
        return "Средняя"
    return "Тяжелая"

df["Категория планеты"] = df["Масса (10^24 кг)"].apply(category_by_mass)
df

In [8]:
# Задание 12: выгрузка в xlsx
df.to_excel("planets_result.xlsx", index=False)
print("Таблица сохранена в planets_result.xlsx")

Таблица сохранена в planets_result.xlsx